import { GlobalVariables } from '../../core/models/globalvariables';
export class ArrivalNotice {
    mbl_pkid: string;
    mbl_book_no: string;
    mbl_no: string;
    mbl_slno: string;
    mbl_book_date: string;
    hbl_blno: string;
    mbl_pol_code: string;
    mbl_pol_name: string;
    mbl_pod_code: string;
    mbl_pod_name: string;
    mbl_carrier_name: string;
    hbl_exp_code: string;
    hbl_exp_name: string;
    hbl_exp_br_no: string;
    hbl_exp_addr1: string;
    hbl_exp_addr2: string;
    hbl_exp_addr3: string;
    hbl_imp_code: string;
    hbl_imp_name: string;
    hbl_imp_br_no: string;
    hbl_imp_addr1: string;
    hbl_imp_addr2: string;
    hbl_imp_addr3: string;
    hbl_terms: string;
    mbl_vessel_code: string;
    mbl_vessel_name: string;
    mbl_vessel_no: string;
    hbl_commodity: string;
    hbl_packages: number;
    hbl_grweight: number;
    hbl_volume: number;
    hbl_selected:boolean;
    mbl_pol_etd: string;
    mbl_pod_eta: string;
    mbl_eta_days: number;
    hbl_ar_notice:string;
    hbl_pkid:string;
    _globalvariables: GlobalVariables;
}
