import { GlobalVariables } from '../../core/models/globalvariables';
export class MoneyTransfer {
    mt_pkid: string;
    mt_jvh_id: string;
    mt_jv_id: string;
    mt_jvh_docno: string;
    mt_type: string;
    mt_txn_mode: string;
    mt_corp_code: string;
    mt_cust_cfno: number;
    mt_cust_uniq_ref: string;
    mt_corp_acc_no: string;
    mt_value_date: string;
    mt_txn_curr: string;
    mt_txn_amt: number;
    mt_party_id: string;
    mt_party_code: string;
    mt_party_name: string;
    mt_ben_id: string;
    mt_ben_name: string;
    mt_ben_code: string;
    mt_ben_acc_no: string;
    mt_ben_acc_type: string;
    mt_ben_addr1: string;
    mt_ben_addr2: string;
    mt_ben_addr3: string;
    mt_ben_city: string;
    mt_ben_state: string;
    mt_ben_pin: string;
    mt_ben_ifsc: string;
    mt_ben_bank_name: string;
    mt_base_code: string;
    mt_chq_no: string;
    mt_chq_date: string;
    mt_payable_loc: string;
    mt_print_loc: string;
    mt_ben_email1: string;
    mt_ben_email2: string;
    mt_ben_mob: string;
    mt_corp_batch_no: string;
    mt_company_code: string;
    mt_product_code: string;
    mt_enrichment1: string;
    mt_enrichment2: string;
    mt_enrichment3: string;
    mt_enrichment4: string;
    mt_enrichment5: string;
    mt_pay_type: string;
    mt_corp_email: string;
    mt_transmission_date: string;
    mt_user_id: string;
    mt_user_dept: string;
    mt_lock: string;
    mt_slno: number;
    mt_format:string;
    mt_selected:boolean;
    mt_remarks:string;
    mt_aprvd:string;
    
    mt_bank_refno:string;
    mt_status_code:string;
    mt_status_desc:string;
    mt_utr:string;

    rec_mode: string;

    _globalvariables: GlobalVariables;
}